In [54]:
import numpy as np

In [2]:
#定义Sigmoid函数
def Sigmoid(x):
    return 1.0 / (1.0+np.exp(-x)) 

In [26]:
#Sigmoid(0)

In [169]:
def bpnetwork(dataset,labels):
    #参数设置
    max_epochs=6000#最大迭代次数
    learn_rate=0.1#学习率
    mse_final=6.5e-4#最小误差，迭代结束的条件
    sample_number=4#样本的数据
    input_number=2#一个样本输入的特征数量
    output_number=1#输出的属性
    hidden_unit_number=4#隐藏层神经元数量
    #隐层阈值
    value1 = 0.5*np.random.rand(hidden_unit_number,1)-0.1
    #输出层阈值
    value2 = 0.5*np.random.rand(output_number,1)-0.1
    #输入层与隐层的连接权重
    weight1 = 0.5*np.random.rand(hidden_unit_number,input_number)-0.1
    
    #隐层与输出层的连接权重
    weight2 = 0.5*np.random.rand(output_number,hidden_unit_number)-0.1
    print(weight2.shape)
    mse_history=[]
    for i in range(max_epochs):
        #fp前向传播
        hidden_out=Sigmoid(np.dot(weight1,dataset)+value1)
        print(hidden_out.shape)
        network_out=np.dot(weight2,hidden_out)+value2
        #误差
        err=labels-network_out
        print(err)
        mse=np.average(np.square(err))
        mse_history.append(mse)
        if mse <mse_final:
            break
        #bp反向传播
        delta2=-err
        print(delta2.shape)
        delta1=delta2.dot(weight2.T)*hidden_out*(1-hidden_out)#weight2的偏导
        # print(delta1.shape)
        delta_weight2=np.dot(delta2,hidden_out.transpose())
        delta_value2=np.dot(delta2,np.ones((sample_number,1)))
        print(delta_weight2)
        delta_weight1=np.dot(delta1,dataset.transpose())
        delta_value1=np.dot(delta1,np.ones((sample_number,1)))
    
        #更新
        weight2-=0.1*delta_weight2
        value2-=learn_rate*delta_value2
        weight1-=learn_rate*delta_weight1
        value1-=learn_rate*delta_value1



In [170]:
#测试
Dataset=np.array([[0,0],
				[0,1],
				[1,1],
				[1,0]]).T
labels=np.array([[0,1,1,0]]).T
bpnetwork(Dataset,labels)


(1, 4)
(4, 4)
[[-0.80194663 -0.8259496  -0.86244142 -0.83904448]
 [ 0.19805337  0.1740504   0.13755858  0.16095552]
 [ 0.19805337  0.1740504   0.13755858  0.16095552]
 [-0.80194663 -0.8259496  -0.86244142 -0.83904448]]
(4, 4)
[[ 1.78235897  2.05611294  1.77320481  2.0098231 ]
 [-0.35498751 -0.41012843 -0.35486667 -0.40380726]
 [-0.35498751 -0.41012843 -0.35486667 -0.40380726]
 [ 1.78235897  2.05611294  1.77320481  2.0098231 ]]


ValueError: non-broadcastable output operand with shape (1,4) doesn't match the broadcast shape (4,4)

(2, 4)