In [1]:
#数据归一化  preprocessing.MinMaxScaler

In [2]:
from sklearn.preprocessing import  MinMaxScaler

In [3]:
#创建数据

In [4]:
data=[[-1,2],[-0.5,6],[0,10],[1,18]]

In [5]:
import pandas as pd

In [6]:
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [7]:
#实现归一化

In [8]:
scaler = MinMaxScaler()#实例化

In [9]:
scaler=scaler.fit(data)#fit 生成，min(x),max(x)

In [10]:
result=scaler.transform(data)

In [11]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [12]:
reslut_=scaler.fit_transform(data)

In [13]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [14]:
#将归一化后的结果还原
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [15]:
#使用MinMaxScaler的参数feature_range实现将数据归一化到[0,1]以外的范围中

In [16]:
data=[[1,2],[-3,2],[4,-5],[1,3]]

In [17]:
pd.DataFrame(data)

0  1
0  1  2
1 -3  2
2  4 -5
3  1  3

In [18]:
scaler=MinMaxScaler(feature_range=[0,1])#依然实例化

In [19]:
result_=scaler.fit_transform(data)#fit_transform一步导出结果

In [20]:
reslut_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

#当X中的特征数量非常多的时候，fit会报错并表示，数据量太大了我计算不了
#此时使用partial_fit作为训练接口
#scaler = scaler.partial_fit(data)

BONUS: 使用numpy来实现归一化

In [21]:
import numpy as np

In [22]:
X = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])

In [23]:
#归一化
X_nor = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [24]:
#逆转归一化
X_returned = X_nor * (X.max(axis=0) - X.min(axis=0)) + X.min(axis=0)
X_returned

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

preprocessing.StandardScaler                                                        当数据(x)按均值(μ)中心化后，再按标准差(σ)缩放，数据就会服从为均值为0，方差为1的正态分布（即标准正态分
布），而这个过程，就叫做数据标准化(Standardization，又称Z-score normalization)，公式如下：

In [25]:
from sklearn.preprocessing import StandardScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [26]:
scaler=StandardScaler()#实例化
scaler.fit(data)#fit，本质是生成均值和方差

StandardScaler()

In [27]:
scaler.mean_#查看均值的属性mean_

array([-0.125,  9.   ])

In [28]:
scaler.var_#查看方差的属性var_

array([ 0.546875, 35.      ])

In [29]:
reslut=scaler.transform(data)

In [30]:
reslut

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [31]:
result.mean()

0.4375

In [32]:
result.std()

0.369754986443726

In [33]:
scaler.fit_transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [34]:
#处理缺失值

In [35]:
import pandas as pd

In [36]:
data=pd.read_csv("Narrativedata.csv",index_col=0)

In [37]:
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       714 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [39]:
Age=data.loc[:,"Age"].values.reshape(-1,1)#sklearn中特征矩阵必须是二维

In [40]:
from sklearn.impute import SimpleImputer
imp_mean=SimpleImputer()
imp_median=SimpleImputer(strategy="median")
imp_0=SimpleImputer(strategy="constant",fill_value=0)

In [41]:
imp_mean=imp_mean.fit_transform(Age)
imp_median=imp_median.fit_transform(Age)
imp_0=imp_0.fit_transform(Age)

In [42]:
imp_mean[:20]

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765]])

In [43]:
imp_median[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [28.],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [28.],
       [31.],
       [28.]])

In [44]:
imp_0[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [ 0.],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [ 0.],
       [31.],
       [ 0.]])

In [45]:
data.loc[:,"Age"]=imp_median
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [46]:
#使用众数填补embarked
Embarked=data.loc[:,"Embarked"].values.reshape(-1,1)

In [47]:
imp_mod=SimpleImputer(strategy="most_frequent")
imp_mod=imp_mod.fit_transform(Embarked)

In [48]:
data.loc[:,"Embarked"]=imp_mod

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [50]:
#使用panad和numpy填补缺失值
import pandas as pd
data_=pd.read_csv("Narrativedata.csv",index_col=0)
data_.loc[:,"Age"]=data_.loc[:,"Age"].fillna(data_.loc[:,"Age"].median())#.fillna 在datafram中直接填补缺失值

In [51]:
data_.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [52]:
#删掉有缺失值的行
data_.dropna(axis=0,inplace=True)

In [53]:
data_.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       889 non-null    float64
 1   Sex       889 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  889 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.7+ KB


In [54]:
#处理分类型特征：编码和哑变量

In [55]:
#preprocessing.LabelEncoder：标签专用，能够将分类转换为分类数值

In [56]:
from sklearn.preprocessing import LabelEncoder
y=data.iloc[:,-1]#要输入的是标签，不是特征矩阵，所以允许是一维

In [57]:
le=LabelEncoder()#实例化
le=le.fit(y)
label=le.transform(y)

In [58]:
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2,
       2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0,
       0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0,
       1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1,
       0, 0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2,

In [59]:
data.iloc[:,-1]=label

In [60]:
data.head

<bound method NDFrame.head of       Age     Sex Embarked  Survived
0    22.0    male        S         0
1    38.0  female        C         2
2    26.0  female        S         2
3    35.0  female        S         2
4    35.0    male        S         0
..    ...     ...      ...       ...
886  27.0    male        S         0
887  19.0  female        S         2
888  28.0  female        S         0
889  26.0    male        C         1
890  32.0    male        Q         0

[891 rows x 4 columns]>

In [61]:
#from sklearn.preprocessing import LabelEncoder
#data.iloc[:,-1]=LabelEncoder.fit_transform(data.[:,-1])#化简代码

In [62]:
#preprocessing.OrdinalEncoder：特征专用，能够将分类特征转换为分类数值
from sklearn.preprocessing import OrdinalEncoder
data_=data.copy()

In [63]:
data_.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [64]:
data.iloc[:,1:-1]=OrdinalEncoder().fit_transform(data.iloc[:,1:-1])

In [65]:
data.head()

Age  Sex  Embarked  Survived
0  22.0  1.0       2.0         0
1  38.0  0.0       0.0         2
2  26.0  0.0       2.0         2
3  35.0  0.0       2.0         2
4  35.0  1.0       2.0         0

In [66]:
#preprocessing.OneHotEncoder：独热编码，创建哑变量
data1=data_.copy()

In [67]:
data1.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [68]:
from sklearn.preprocessing import OneHotEncoder
X=data1.iloc[:,1:-1]

In [69]:
enc=OneHotEncoder(categories='auto').fit(X)
reslut=enc.transform(X).toarray()


In [70]:
reslut

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [71]:
#axis=1,表示跨行进行合并，也就是将量表左右相连，如果是axis=0，就是将量表上下相连
enc.inverse_transform(reslut)

array([['male', 'S'],
       ['female', 'C'],
       ['female', 'S'],
       ...,
       ['female', 'S'],
       ['male', 'C'],
       ['male', 'Q']], dtype=object)

In [72]:
enc.get_feature_names()

E:\anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


array(['x0_female', 'x0_male', 'x1_C', 'x1_Q', 'x1_S'], dtype=object)

In [73]:
reslut

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [74]:
newdata = pd.concat([data1,pd.DataFrame(reslut)],axis=1)

In [75]:
newdata

Age     Sex Embarked  Survived    0    1    2    3    4
0    22.0    male        S         0  0.0  1.0  0.0  0.0  1.0
1    38.0  female        C         2  1.0  0.0  1.0  0.0  0.0
2    26.0  female        S         2  1.0  0.0  0.0  0.0  1.0
3    35.0  female        S         2  1.0  0.0  0.0  0.0  1.0
4    35.0    male        S         0  0.0  1.0  0.0  0.0  1.0
..    ...     ...      ...       ...  ...  ...  ...  ...  ...
886  27.0    male        S         0  0.0  1.0  0.0  0.0  1.0
887  19.0  female        S         2  1.0  0.0  0.0  0.0  1.0
888  28.0  female        S         0  1.0  0.0  0.0  0.0  1.0
889  26.0    male        C         1  0.0  1.0  1.0  0.0  0.0
890  32.0    male        Q         0  0.0  1.0  0.0  1.0  0.0

[891 rows x 9 columns]

In [76]:
newdata.drop(["Sex","Embarked"],axis=1,inplace=True)

In [77]:
newdata.columns = ["Age","Survived","Female","Male","Embarked_C","Embarked_Q","Embarked_S"]
newdata.head()

Age  Survived  Female  Male  Embarked_C  Embarked_Q  Embarked_S
0  22.0         0     0.0   1.0         0.0         0.0         1.0
1  38.0         2     1.0   0.0         1.0         0.0         0.0
2  26.0         2     1.0   0.0         0.0         0.0         1.0
3  35.0         2     1.0   0.0         0.0         0.0         1.0
4  35.0         0     0.0   1.0         0.0         0.0         1.0

In [78]:
#处理连续型特征：二值化与分段

In [79]:
#sklearn.preprocessing.Binarizer

In [80]:
from sklearn.preprocessing import Binarizer

In [81]:
data_2=data_.copy()

In [82]:
data_2

Age     Sex Embarked  Survived
0    22.0    male        S         0
1    38.0  female        C         2
2    26.0  female        S         2
3    35.0  female        S         2
4    35.0    male        S         0
..    ...     ...      ...       ...
886  27.0    male        S         0
887  19.0  female        S         2
888  28.0  female        S         0
889  26.0    male        C         1
890  32.0    male        Q         0

[891 rows x 4 columns]

In [83]:
X=data_2.iloc[:,0].values.reshape(-1,1)

In [84]:
t1=Binarizer(threshold=30).fit_transform(X)
data_2.iloc[:,0]=t1

In [85]:
data_2

Age     Sex Embarked  Survived
0    0.0    male        S         0
1    1.0  female        C         2
2    0.0  female        S         2
3    1.0  female        S         2
4    1.0    male        S         0
..   ...     ...      ...       ...
886  0.0    male        S         0
887  0.0  female        S         2
888  0.0  female        S         0
889  0.0    male        C         1
890  1.0    male        Q         0

[891 rows x 4 columns]

In [86]:
#分箱 preprocessing.KBinsDiscretizer

In [87]:
from sklearn.preprocessing import KBinsDiscretizer
data_3=data_.copy()

In [88]:
data_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    int32  
dtypes: float64(1), int32(1), object(2)
memory usage: 31.3+ KB


In [89]:
X=data.iloc[:,0].values.reshape(-1,1)

In [90]:
est=KBinsDiscretizer(n_bins=3,encode='ordinal',strategy='uniform')
est.fit_transform(X)

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [91]:
set(est.fit_transform(X).ravel())

{0.0, 1.0, 2.0}

In [96]:
est=KBinsDiscretizer(n_bins=3,encode='onehot',strategy='uniform')
est.fit_transform(X).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [103]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.feature_selection import VarianceThreshold
data=pd.read_csv("digit recognizor.csv")

In [104]:
X=data.iloc[:,1:]
y=data.iloc[:,0]
X_fsvar = VarianceThreshold(np.median(X.var().values)).fit_transform(X)

In [105]:
cross_val_score(KNN(),X_fsvar,y,cv=5).mean()

0.966

In [106]:
%%timeit
cross_val_score(KNN(),X,y,cv=5).mean()

1min 12s ± 18.6 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
